name: api tests

on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ubuntu-latest

    
    steps:  
     - name: Checkout
       uses: actions/checkout@v2.0.0
     - name: View repository
       run: ls && cd myproject && ls
     - name: Set up JDK 17
       uses: actions/setup-java@v3
       with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven  
     - name: Build with Maven
       run: |
         cd myproject
         ls
         mvn clean test "-Dkarate.options=--tags @debug"
     - name: Karate DSL test reports
       uses: actions/upload-artifact@v2
       if: ${{ always() }}
       with: 
         name: Test reports
         path: 
           ///home/runner/work/KarateTemplate/KarateTemplate/myproject/target/karate-reports/karate-summary.html
         
         
       
     


    
